config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_scope :user do
    unauthenticated :user do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  authenticated :user do
    root to: 'recipes#index', as: :authenticated_root
  end

  resources :recipes do
    resources :comments, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
  belongs_to :parent, class_name:'Comment', optional: true
  has_many :comments, foreign_key: :parent_id
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    belongs_to :user
    validates :user, presence: true
    has_many :comments, dependent: :destroy

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    protected
    def after_sign_in_path_for(resource)
        recipes_path
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
        @comment = current_user.comments.new(comment_params)

        if !@comment.save
            flash[:notice] = @comment.errors.full_messages.to_sentence
        end
        redirect_to recipe_path(params[:recipe_id])
    end

    private
    def comment_params
        params.require(:comment).permit(:context).merge(recipe_id: params[:recipe_id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!, only: %i[ create ]

  def index
    @recipes = Recipe.all
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)
    if @recipe.save
      redirect_to @recipe
    else
      render :new, status: :unprocessable_identity
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      puts @recipe.errors.full_messages
      render :edit, status: :unprocessable_identity
    end
  end

  def destroy
    if @recipe.user == current_user
      @recipe.destroy
      redirect_to recipes_path
    else
      redirect_to recipes_path, alert: "Not authorized"
    end
  end

  private
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :prep_time, :cook_time, :servings, :difficulty, :cuisine_type, :category, :instructions)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_comment.html.erb
<article>
    <small> <%= comment.context %> </small> <br />
    <small> By <%= comment.user.email %> </small>
    <hr />
</article>

app/views/comments/_form.html.erb
<form action="<%= recipe_comments_path(recipe) %>" method="post">
    <input type="hidden" name="authenticity_token" value="form_authenticity_token">
    <textarea name= "comment[context]" cols="20" rows="6"> </textarea>
    <input type="Submit" value="Submit">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsBackendCookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, data: {"turbo-method": :delete} %>
        <%= link_to "Edit Profile", edit_user_registration_path %>
      <% end %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= stylesheet_link_tag "form" %>
<div class="recipe-entry-container">
<%= form_with model: recipe do |form| %>
    <div class="recipe-entry">
        <%= form.label :name %>
        <%= form.text_field :name, required: true, placeholder:"Enter Recipe Name", class:"form-control"%>
    </div>
    <div class="scroll-inputs">
        <div class="recipe-entry">
            <%= form.label :prep_time %>
            <%= form.number_field :prep_time, min:1, step:1, value:5, class:"form-control" %>
        </div>
        <div class="recipe-entry">
            <%= form.label :cook_time %>
            <%= form.number_field :cook_time, min:1, step:1, value:2, class:"form-control" %>
        </div>
        <div class="recipe-entry">
            <%= form.label :servings %>
            <%= form.number_field :servings, min:1, max: 200, step:1, value:1, class:"form-control" %>
        </div>
    </div>
    <div class="drop-inputs">
        <div class="recipe-entry">
            <%= form.label :Difficulty %>
            <%= form.select :difficulty, options_for_select(['easy', 'medium', 'hard']), prompt: "Select difficulty", class:"form-control" %>
        </div>
        <div class="recipe-entry">
            <%= form.label :category %>
            <%= form.select :category, options_for_select([ 'Breakfast', 'Lunch', 'Dinner', 'Dessert', 'Snack', 'None Apply']), class:"form-control" %>
        </div>
        <div class="recipe-entry">
        <%= form.label :cuisine_type %>
        <%= form.text_field :cuisine_type, placeholder:"Input Cuisine Type", class:"form-control" %>
    </div>
    </div>
    <div class="recipe-entry">
        <div class="instructions">
        <%= form.label :instructions %>
        <%= form.text_field :instructions, placeholder: "Enter Recipe Instructions", class:"form-control-instructions" %>
        </div>
    </div>
    <div class="recipe-submit">
        <%= form.submit %>
    </div>
<% end %>
</div>

app/views/recipes/edit.html.erb
<%= stylesheet_link_tag "form" %>
<h> Edit Recipe </h>
<%= render "form", recipe: @recipe %>
<%= link_to "Cancel", @recipe, class:'cancel-btn'%>

app/views/recipes/index.html.erb
<%= stylesheet_link_tag "home" %>
<h1>Recipes</h1>
<%= link_to "Create New Recipe", new_recipe_path, class:'new-btn' %>
<div class="recipes">
    <% @recipes.each do |recipe| %>
        <div>
            <%= link_to recipe.name, recipe, class:'recipe-entry' %>
        </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<h> New Recipe </h>
<%= render "form", recipe: @recipe %>
<%= link_to "Cancel", recipes_path, class:'cancel-btn' %>

app/views/recipes/show.html.erb
<div class="recipe">
    <h2><%= @recipe.name %></h2>
    <h3> Servings: <%=@recipe.servings %> </h3>
    <h3> Cook Time: <%=@recipe.cook_time %> </h3>
    <h3> Prep Time: <%=@recipe.prep_time %> </h3>
    <h3> difficulty: <%=@recipe.difficulty %> </h3>
    <h3> cuisine_type: <%=@recipe.cuisine_type %> </h3>
    <h3> category: <%=@recipe.category %> </h3>
    <h3> instructions: <%=@recipe.instructions %> </h3>
    <h3> Recipe Author: <%=@recipe.user.email %> </h3>
    <div class="btn-options">
        <%= link_to "Back", recipes_path, class:'std-btn' %>
        <% if @recipe.user == current_user %>
            <%= link_to "Edit", edit_recipe_path(@recipe), class:'new-btn' %>
            <%= button_to "Delete", @recipe, method: :delete, data: {turbo_confirm: "Are you sure"}, class:'cancel-btn' %>
        <% end %>
    </div>
    <p>
        <strong> Comments </strong>
        <%= render @recipe.comments%>
        <%= render partial: 'comments/form', locals: {recipe: @recipe}%>
    </p>
</div>